# Generated by Django 3.2.13 on 2022-06-19 16:47

import datetime
from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('usergroup', models.CharField(choices=[('Sale', 'Sale role'), ('Support', 'Support role'), ('Management', 'Management role'), ('Default', 'Unassigned')], default='Default', max_length=15, verbose_name=user_management.models.UserModel.UserGroup)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
