# Generated by Django 3.2.13 on 2022-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_model',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='user_model',
            name='usergroup',
            field=models.CharField(choices=[('Sale', 'Sale role'), ('Support', 'Support role'), ('Management', 'Management role'), ('Default', 'No role assigned')], default='Default', max_length=15, verbose_name='UserGroup'),
        ),
    ]
