# Generated by Django 3.2.13 on 2022-05-30 13:27

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20220530_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='usergroup',
            field=models.CharField(choices=[('Sale', 'Sale role'), ('Support', 'Support role'), ('Management', 'Management role'), ('Default', 'No role assigned')], default='Default', max_length=15, verbose_name=user_management.models.User_Model.UserGroup),
        ),
    ]
