# Generated by Django 3.2.13 on 2022-06-03 11:10

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_model_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='usergroup',
            field=models.CharField(choices=[('Sale', 'Sale role'), ('Support', 'Support role'), ('Management', 'Management role'), ('Default', 'Unassigned')], default='Default', max_length=15, verbose_name=user_management.models.User_Model.UserGroup),
        ),
    ]
