# Generated by Django 3.2.13 on 2022-06-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20220603_1440'),
        ('user_management', '0004_alter_user_model_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'usergroup': 'Sale'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.user_model')),
            ],
        ),
    ]
