# Generated by Django 4.1 on 2022-08-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_prospect'),
        ('contracts', '0002_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_prospect': False}, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
