# Generated by Django 3.2.13 on 2022-06-05 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20220603_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 17, 46, 38, 327049)),
        ),
    ]
