# Generated by Django 3.2.13 on 2022-06-06 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 16, 6, 14, 437071)),
        ),
    ]
