# Generated by Django 3.2.13 on 2022-06-03 11:54

from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0004_alter_user_model_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'usergroup': user_management.models.User_Model}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.user_model')),
            ],
        ),
    ]
